name: haptic_feedback_example

description: Demonstrates how to use the haptic_feedback plugin.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ^3.12.0
  flutter: '>=3.47.0'

dependencies:
  flutter:
    sdk: flutter

  haptic_feedback:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

flutter:
    uses-material-design: true
